---@module 'which-key'

return {
  {
    "folke/which-key.nvim",
    event = "VimEnter",
    ---@type wk.Opts
    opts = {
      delay = 0,
      icons = {
        mappings = vim.g.have_nerd_font,
        keys = vim.g.have_nerd_font and {} or {
          Up = "<Up> ",
          Down = "<Down> ",
          Left = "<Left> ",
          Right = "<Right> ",
          C = "<C-…> ",
          M = "<M-…> ",
          D = "<D-…> ",
          S = "<S-…> ",
          CR = "<CR> ",
          Esc = "<Esc> ",
          ScrollWheelDown = "<ScrollWheelDown> ",
          ScrollWheelUp = "<ScrollWheelUp> ",
          NL = "<NL> ",
          BS = "<BS> ",
          Space = "<Space> ",
          Tab = "<Tab> ",
          F1 = "<F1>",
          F2 = "<F2>",
          F3 = "<F3>",
          F4 = "<F4>",
          F5 = "<F5>",
          F6 = "<F6>",
          F7 = "<F7>",
          F8 = "<F8>",
          F9 = "<F9>",
          F10 = "<F10>",
          F11 = "<F11>",
          F12 = "<F12>",
        },
      },
      spec = {
        -- only keymap groups defined here; actual keymaps defined elsewhere
        { "<leader>d", group = "Debug" },
        { "<leader>f", group = "Find" },
        { "<leader>fp", group = "Picker" },
        { "<leader>g", group = "Git", mode = { "n", "x" } },
        { "<leader>gd", group = "Diff", mode = { "n", "x" } },
        { "<leader>gf", group = "Find", mode = { "n", "x" } },
        { "<leader>gh", group = "GitHub", mode = { "n", "x" } },
        { "<leader>gg", group = "Lazygit", mode = { "n", "x" } },
        { "<leader>gr", group = "Reset", mode = { "n", "x" } },
        { "<leader>gs", group = "Stage", mode = { "n", "x" } },
        { "<leader>l", group = "LSP", mode = { "n", "x" } },
        { "<leader>lg", group = "Goto", mode = { "n", "x" } },
        { "<leader>ls", group = "Search", mode = { "n", "x" } },
        { "<leader>lr", group = "Rename", mode = { "n", "x" } },
        { "<leader>m", group = "Move window" },
        { "<leader>n", group = "Notifications" },
        { "<leader>p", group = "Profiler" },
        { "<leader>s", group = "Search", mode = { "n", "x" } },
        { "<leader>S", group = "Scratch" },
        { "<leader>t", group = "Trouble" },
        { "<leader>T", group = "Toggles" },
        { "<leader>To", group = "Options" },
        { "<leader>Tp", group = "Profiler" },
        { "<leader>.", group = "Terminal" },
        { "<leader>.f", group = "Floating" },
        { "<leader>.v", group = "Vertical split" },
        { "<leader>.h", group = "Horizontal split" },
      },
      win = {
        border = "rounded",
      },
    },
  },
}
-- vim: ts=2 sts=2 sw=2 et
